name: C Linux CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install_cblas
      run: sudo apt update && sudo apt install libatlas3-base libatlas-base-dev libblas-dev libblas3
    - name: make
      run: make
    - name: make run
      run: make run
    # - name: make test
    #   run: make test
